version: "3"

services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - JWT_SECRET=secret

      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_DB=challenge_db

      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=admin
      - RMQ_PASS=admin
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  tasks-service:
    container_name: tasks-service
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - JWT_SECRET=secret

      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_DB=challenge_db

      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=admin
      - RMQ_PASS=admin
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      network: host
    restart: always
    network_mode: host
    ports:
      - 3334:3334
    environment:
      - NODE_ENV=production
      - PORT=3333
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=admin
      - RMQ_PASS=admin
    depends_on:
      auth-service:
        condition: service_started
      tasks-service:
        condition: service_started
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # Postgres Database
  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    attach: false
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge_db

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    attach: false
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes: ["rabbitmq_data:/var/lib/rabbitmq"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 15s
      retries: 10

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
